DROP TABLE IF EXISTS client;
 
CREATE TABLE client (
  id LONG AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  lastLogin VARCHAR(250) NOT NULL,
  roles VARCHAR(250) NOT NULL
);
 